### ISSUE TITLE
error while deploying yaml file using kubectl command on instance

### ISSUE THREAD

**Issue by PallaviTharigonda** [sumichaaan/free5gc-k8s#3]
Hi,
  I'm getting the following error:
$kubectl apply -f 01_init_defaults.yaml 
error: error parsing 01_init_defaults.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"K8S_API_ADVERTISE_ADDRESS":interface {}(nil)}

I tried searching on google but didn't find anything helpful.Can you please help me with this issue?

**Comment by infinitydon** [comment]
This file should be used to create a kubernetes cluster using kubeadm.

You are not supposed to use this in an existing kubernetes cluster, it's a kubeadm installation configuration file

**Comment by PallaviTharigonda** [comment]
Can you please tell the steps for deploying free5gc to exisitng k8 scluster?

**Comment by infinitydon** [comment]
The manifests can be found at:

https://github.com/sumichaaan/free5gc-k8s/tree/master/manifests

**Comment by nmpvinh** [comment]
Hi @infinitydon ;

Sorry for this interruption, i'm trying to understand how i can utilize this k8s to create a helm chart for this, Could you possibly shed some light and help me with this?

Thanks.

**Comment by infinitydon** [comment]
@nmpvinh There is no need to use helm charts, the manifest files are using kustomize (https://kustomize.io/), you can deploy the amf for example using the kustomize option of the kubectl command:

**kubectl apply -k f5gc-amf/**

**Comment by PallaviTharigonda** [comment]
@infinitydon I've tried deploying on existing cluster 
/free5gc-k8s/manifests/f5gc-smf$ kubectl apply -f kustomization.yaml 
error: error validating "kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

I'm getting this kinda error

Also I tried setting validate=false

/free5gc-k8s/manifests/f5gc-smf$ kubectl apply --validate=false -f kustomization.yaml 
error: unable to decode "kustomization.yaml": Object 'Kind' is missing in '{"generatorOptions":{"disableNameSuffixHash":true},"namespace":"f5gc","resources":["00_smf-sa.yaml","01_smf-rbac.yaml","02_smf-configmap.yaml","03_smf-service.yaml","04_smf-multus.yaml","05_smf-deployment.yaml"],"secretGenerator":[{"files":["cert/smf.pem","cert/smf.key"],"name":"f5gc-smf-tls-secret","namespace":"free5gc","type":"Opaque"}]}'

I'm getting this error.

Please can you help with this :)

or Tell me if you want me to try another method.

**Comment by infinitydon** [comment]
@PallaviTharigonda That is not the procedure

Create the namespace first: **kubectl create -f 00_namespace.yaml**

Then create free5gc components e.g for AMF: **kubectl apply -k f5gc-amf/**

**Comment by PallaviTharigonda** [comment]
@infinitydon I tried this,but still there are some errors
~/free5gc-k8s/manifests$ kubectl apply -k f5gc-amf/
serviceaccount/f5gc-amf-sa created
clusterrolebinding.rbac.authorization.k8s.io/f5gc-amf-rbac created
configmap/f5gc-amf-config created
secret/f5gc-amf-tls-secret created
unable to recognize "f5gc-amf/": no matches for kind "NetworkAttachmentDefinition" in version "k8s.cni.cncf.io/v1"
Error from server (Invalid): error when creating "f5gc-amf/": Service "f5gc-amf" is invalid: spec.ports[1].protocol: Unsupported value: "SCTP": supported values: "TCP", "UDP"
Error from server (Invalid): error when creating "f5gc-amf/": Deployment.apps "f5gc-amf" is invalid: spec.template.spec.containers[0].ports[1].protocol: Unsupported value: "SCTP": supported values: "TCP", "UDP"

Can you please tell me why am I getting these error?

**Comment by PallaviTharigonda** [comment]
@infinitydon Thanks a ton.It's working fine .services are coming up.

Is there any way to make communication in between the services?

**Comment by infinitydon** [comment]
@PallaviTharigonda What do you mean by communication between the services? Services should be able to communicate normally.

**Comment by PallaviTharigonda** [comment]
@infinitydon I'm getting some errors like 
  Type     Reason   Age                      From     Message
  ----     ------   ----                     ----     -------
  Warning  Failed   8m35s (x814 over 3h13m)  kubelet  Error: ImagePullBackOff
  Normal   BackOff  3m30s (x837 over 3h13m)  kubelet  Back-off pulling image "ghcr.io/sumichaaan/free5gc-k8s/f5gc-smf:v3.0.4"

![Screenshot (54)](https://user-images.githubusercontent.com/46990042/110758359-7245ed00-8272-11eb-925d-3bc607b583e5.png)

why it's not pulling image?

**Comment by PallaviTharigonda** [comment]
Hi @infinitydon .My 5gc pods are not running properly.
kubectl get pods --namespace=f5gc
NAME                                 READY   STATUS             RESTARTS   AGE
dbg-mongo-express-668dc8dd65-q4xdl   1/1     Running            2          4m8s
dbg-rockmongo-d8668c5b5-85dnw        1/1     Running            0          4m16s
f5gc-amf-b8c8d979c-xm7q7             1/2     ImagePullBackOff   0          4m42s
f5gc-ausf-6d6c879bc7-zmx8g           1/2     ImagePullBackOff   0          3m51s
f5gc-mongodb-0                       1/1     Running            0          3m43s
f5gc-n6dummy-2-69fb784f49-mfdx2      1/1     Running            0          3m28s
f5gc-n6dummy-6f64cc784c-lxfgx        1/1     Running            0          3m19s
f5gc-nrf-5585c6f748-w82m9            1/2     ImagePullBackOff   0          2m14s
f5gc-nssf-58b4f7cbf9-rwg5v           1/2     ErrImagePull       0          3m11s
f5gc-pcf-7bc6fd8c86-6jmbp            1/2     ImagePullBackOff   0          2m9s
f5gc-smf-2-5ffb4788d7-vdd6t          1/2     ImagePullBackOff   0          2m
f5gc-smf-5fd75d47ff-xqx48            1/2     ImagePullBackOff   0          3m4s
f5gc-udm-56865b48bb-xdv6w            1/2     ImagePullBackOff   0          2m58s
f5gc-udr-55c569c8c5-mk692            1/2     ErrImagePull       0          110s
f5gc-upf-2-b4fd7764f-6k59b           1/2     ImagePullBackOff   0          102s
f5gc-upf-56f4fd47c8-cmmq8            1/2     ImagePullBackOff   0          2m45s
f5gc-webui-587bfb978c-8ftmk          1/2     ImagePullBackOff   0          2m35s

Can you please look at this and tell me why I'm getting like this.

**Comment by PallaviTharigonda** [comment]
Hi @infinitydon ,images are not pulling properly for me & pods are also not running.So I tried changing image name in "05_upf-deployment.yaml" from "ghcr.io/sumichaaan/free5gc-k8s/f5gc-upf:v3.0.4" to "docker.io/free5gc/upf".So now I can able to pull image but I'm getting error "Back-off restarting failed container".
Here I'm attaching the snapshot of that issue.

![Screenshot (57)](https://user-images.githubusercontent.com/46990042/111116313-dc6cd380-858b-11eb-8d5a-cc444f7f163a.png)

and regarding pods

![image](https://user-images.githubusercontent.com/46990042/111116427-04f4cd80-858c-11eb-9141-98224442b3c3.png)

Can you please help me with this issue?

**Comment by infinitydon** [comment]
@PallaviTharigonda - I suggest you try the following manifests:

https://github.com/free5gmano/free5gmano/tree/master/deploy/free5gc-stage-3.0.4/k8s-cni

**Comment by PallaviTharigonda** [comment]
@infinitydon thank you for providing the link.Now my pods are coming up.

how can i check the communication is working between UPF and SMF based on PFCP.

I went inside the container and check logs for smf ..there I can see pfcp is sending 
![image](https://user-images.githubusercontent.com/46990042/111300370-051dc780-8677-11eb-98f0-0adfb8018f44.png)

but at the receiver side upf, I can't see any logs.
![image](https://user-images.githubusercontent.com/46990042/111300547-35656600-8677-11eb-8ba2-97924aec34f2.png)

should upf & smf should be in  a same container?Can you please help me out.

**Comment by infinitydon** [comment]
@PallaviTharigonda I suggest you close this current issue because you are no longer using the manifests from this repo.

You can ping on [linkedin ](https://www.linkedin.com/in/christopher-gbenga-adigun-731b8115/) for further communication on this.
